version: '3.9'

services:
  plex:
    image: 'linuxserver/plex'
    container_name: 'plex'
    restart: 'unless-stopped'
    environment:
        - PGID=1000
        - PUID=1000
        - TZ=PST
        - VERSION=docker
        - ADVERTISE_IP="https://plex.pi.lan"
        - SYSCALL_MAX_ENABLED=1
    ports:
      - 32400:32400/tcp
      - 32400:32400/udp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - 'plex-data:/config'
      - 'plex-trans-data:/transcode'
      #- './data/:/data/'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.plex.rule=Host(`plex.pi.lan`)'
      - 'traefik.http.routers.plex.entrypoints=web-secure'
      - 'traefik.http.routers.plex.service=plexService'
      - 'traefik.http.services.plexService.loadBalancer.server.port=32400'

volumes:
  plex-data:
  plex-trans-data:

networks:
  default:
    external: true
    name: homeinfra-net